### ISSUE TITLE
UnhandledPromiseRejection -- MSSQLStore.ready

### ISSUE THREAD

**Issue by JLuboff** [JLuboff/connect-mssql-v2#11]
While idle, experienced an UnhandledPromiseRejectionWarning: TypeError: callback is not a function. 
Calling function - MSSQLStore.ready (private method)

**Comment by bradtaniguchi** [comment]
When re-doing the types I noticed that all the `callback` parameters in the store methods **could** be undefined. I didn't include this in the types settings as I assume everything was working properly. 

Since the code is always executing the `callback` parameter that **might** be the problem. (it could be `undefined` or `null` or something being passed instead)

**Comment by JLuboff** [comment]
That's a good point. I was thinking I have catch blocks every where, so errors should be handled but you're right, if `callback` is undefined, its going to throw an unhandled rejection. Perhaps I create an additional event listener `this.databaseConnection.on('error', error => this.emit('error', error));` and emit that in the catch blocks and only return the `callback` with the error if `callback` is not undefined.

**Comment by JLuboff** [comment]
Reopening issue as I am still getting `TypeError: callback is not a function` once hourly.
