### ISSUE TITLE
Is it possible to use it with msnodesqlv8 and Windows Authentication? (Trusted Connection)

### ISSUE THREAD

**Issue by ITSNOTSTUPIDIFITWORKS** [JLuboff/connect-mssql-v2#56]
How can i use Windows Authentication. (Trusted Connection)?

**Comment by JLuboff** [comment]
There is currently no plans in place to implement the use of the `msnodesqlv8` driver. 
Looking at the [mssql docs on msnodesqlv8 driver](https://www.npmjs.com/package/mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server), it looks like it would require a decent rewrite or a separate class to implement as all imports will need to be changed. 

We are open to contributions if you'd like to work this out. I am no longer working with MS SQL so any new features may not be implemented or at least not in a timely fashion from myself. I will still be doing my best to keep packages up to date which do not introduce breaking changes.

**Comment by bommulurianji2** [comment]
Expected behavior:

The Node.js application should connect to the MS SQL server on a internal environment with the development account using the Kerberos authentication scheme.

Actual behavior:

The Node.js application is not connecting to the MS SQL server on internal environment with the development account using the Kerberos authentication scheme.

I don't find a way to mention the scheme and the relevant drivers..

for example : authPlugins: {
authentication_kerberos_client: plugins.authentication_kerberos_client()

Configuration:

currently using something like this which is working in terms of connection, But when we add the development id not working..

----working sample ------
const sql = require("msnodesqlv8");

const connectionString = "server=.;Database=Master;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";
const query = "SELECT name FROM sys.databases";

sql.query(connectionString, query, (err, rows) => {
console.log(rows);
});
----Not working sample ------

const sql = require("msnodesqlv8");

const connectionString = "server=.;Database=Master;User=developmentID;Trusted_Connection=Yes;Driver={SQL Server Native Client 11.0}";
const query = "SELECT name FROM sys.databases";

sql.query(connectionString, query, (err, rows) => {
console.log(rows);
})

Software versions

NodeJS: Node 18.15.0

node-mssql:msnodesqlv8

SQL Server:SQL Server 2019

**Comment by bommulurianji2** [comment]
Any idea we have Kerberos as authentication scheme that can be used?

**Comment by bradtaniguchi** [comment]
Closing this as stale. Open a new issue if the issue/question is still around! Thanks!
